const fs = require('fs');
const lines = fs.readFileSync('src/Exams.jsx','utf8').split('\n');
const scheduleTable = [
'function ScheduleTable({ schedule, examTypes, courses, filterCourse, setFilterCourse, filterExamType, setFilterExamType, onDelete, selectable, selected, onToggle, onSelectAll, onDeselectAll }) {',
'  return (',
'    <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>',
'      <div style={{ display: "flex", gap: 12, flexWrap: "wrap", alignItems: "flex-end" }}>',
'        <div>',
'          <label style={{ display: "block", fontSize: 11, fontWeight: 700, color: "#6B7280", marginBottom: 5, textTransform: "uppercase" }}>Filter Course</label>',
'          <div style={{ display: "flex", gap: 5, flexWrap: "wrap" }}>',
'            {["ALL", ...courses].map(c => (',
'              <button key={c} onClick={() => setFilterCourse(c)}',
'                style={{ ...css.btn, padding: "5px 12px", fontSize: 11, background: filterCourse === c ? "#1a3c2e" : "#F3F4F6", color: filterCourse === c ? "white" : "#374151", border: filterCourse === c ? "none" : "1px solid #E5E7EB" }}>{c}</button>',
'            ))}',
'          </div>',
'        </div>',
'        <div>',
'          <label style={{ display: "block", fontSize: 11, fontWeight: 700, color: "#6B7280", marginBottom: 5, textTransform: "uppercase" }}>Filter Exam Type</label>',
'          <select value={filterExamType} onChange={e => setFilterExamType(e.target.value)} style={{ ...css.input, width: 180 }}>',
'            <option value="ALL">All Types</option>',
'            {examTypes.map(et => <option key={et.id} value={et.id}>{et.name}</option>)}',
'          </select>',
'        </div>',
'        {selectable && (',
'          <div style={{ display: "flex", gap: 6 }}>',
'            <button onClick={onSelectAll} style={{ ...css.btn, padding: "5px 12px", fontSize: 11, background: "#E0F2FE", color: "#0369A1" }}>Select All</button>',
'            <button onClick={onDeselectAll} style={{ ...css.btn, padding: "5px 12px", fontSize: 11, background: "#FEF2F2", color: "#DC2626" }}>Deselect All</button>',
'          </div>',
'        )}',
'        <div style={{ fontSize: 12, color: "#9CA3AF", alignSelf: "center" }}>{schedule.length} entries</div>',
'      </div>',
'      <div style={{ background: "white", borderRadius: 12, boxShadow: "0 2px 8px rgba(0,0,0,0.07)", overflow: "hidden" }}>',
'        <div style={{ padding: "12px 18px", background: "#1a3c2e", color: "white", fontWeight: 700, fontSize: 13 }}>📅 Exam Schedule</div>',
'        <div style={{ overflowX: "auto" }}>',
'          <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>',
'            <thead><tr style={{ background: "#F8FAFC", borderBottom: "2px solid #E5E7EB" }}>',
'              {selectable && <th style={{ padding: "10px 12px", width: 36 }}></th>}',
'              {["Date","Course","Exam Type","Subject","Shift","Time","Marks","Room",""].map(h => (',
'                <th key={h} style={{ padding: "10px 12px", textAlign: "left", fontWeight: 700, color: "#374151", fontSize: 11 }}>{h}</th>',
'              ))}',
'            </tr></thead>',
'            <tbody>',
'              {schedule.map((s, i) => (',
'                <tr key={s.id} style={{ background: selectable && selected && selected.has(s.id) ? "#EFF6FF" : i % 2 ? "#F9FAFB" : "white", borderBottom: "1px solid #F1F5F9" }}>',
'                  {selectable && (',
'                    <td style={{ padding: "9px 12px", textAlign: "center" }}>',
'                      <input type="checkbox" checked={selected && selected.has(s.id) || false} onChange={() => onToggle(s.id)} />',
'                    </td>',
'                  )}',
'                  <td style={{ padding: "9px 12px", fontWeight: 600 }}>{s.exam_date}</td>',
'                  <td style={{ padding: "9px 12px" }}><span style={{ background: "#E1F5EE", color: "#0F6E56", padding: "2px 8px", borderRadius: 999, fontSize: 11, fontWeight: 700 }}>{s.course || "—"}</span></td>',
'                  <td style={{ padding: "9px 12px" }}>{examTypes.find(e => e.id === s.exam_type_id)?.name || s.exam_type_id}</td>',
'                  <td style={{ padding: "9px 12px" }}>{s.subject}</td>',
'                  <td style={{ padding: "9px 12px", color: "#64748b" }}>{s.shift || "Morning"}</td>',
'                  <td style={{ padding: "9px 12px", color: "#64748b" }}>{s.time || "--"}</td>',
'                  <td style={{ padding: "9px 12px", color: "#64748b" }}>{s.total_marks}</td>',
'                  <td style={{ padding: "9px 12px", color: "#64748b" }}>{s.room || "--"}</td>',
'                  <td style={{ padding: "9px 12px" }}>',
'                    <button onClick={() => onDelete(s.id)} style={{ ...css.btn, padding: "4px 10px", background: "#FEF2F2", color: "#DC2626", border: "1px solid #FECACA", fontSize: 12 }}>✕</button>',
'                  </td>',
'                </tr>',
'              ))}',
'              {!schedule.length && <tr><td colSpan={selectable ? 10 : 9} style={{ padding: 32, textAlign: "center", color: "#94A3B8" }}>No schedule entries yet.</td></tr>}',
'            </tbody>',
'          </table>',
'        </div>',
'      </div>',
'    </div>',
'  );',
'}',
];
lines.splice(2652, 0, ...scheduleTable);
fs.writeFileSync('src/Exams.jsx', lines.join('\n'));
console.log('Done - inserted ScheduleTable at line 2652');
